import type {
  OceanAreaDef,
  OceanAreaId,
  OceanResourceId,
} from "@/lib/ocean/contracts";

export const OCEAN_OFFLINE_CAP_MS = 8 * 60 * 60 * 1000;

export const oceanResources: Record<
  OceanResourceId,
  { name: string; icon: string; color: string }
> = {
  fish: { name: "小魚", icon: "🐟", color: "#7dd3fc" },
  grilled: { name: "焼き魚", icon: "🍢", color: "#fbbf24" },
  shell: { name: "真珠貝", icon: "🐚", color: "#f9a8d4" },
  pearl: { name: "真珠", icon: "⚪", color: "#f8fafc" },
  tuna: { name: "マグロ", icon: "🐟", color: "#60a5fa" },
  frozen: { name: "冷凍マグロ", icon: "🧊", color: "#bfdbfe" },
  plankton: { name: "外洋プランクトン", icon: "🦠", color: "#86efac" },
  biofuel: { name: "バイオ燃料", icon: "🔋", color: "#4ade80" },
  deepOre: { name: "深海鉱石", icon: "🪨", color: "#a78bfa" },
  alloy: { name: "耐圧合金", icon: "🔩", color: "#cbd5e1" },
  heatOre: { name: "熱鉱石", icon: "🌋", color: "#fb7185" },
  core: { name: "地熱コア", icon: "☀️", color: "#fb923c" },
  iceFish: { name: "氷海魚", icon: "🐠", color: "#a5f3fc" },
  cityPart: { name: "海底都市パーツ", icon: "🏙️", color: "#ddd6fe" },
};

export const oceanAreas: OceanAreaDef[] = [
  {
    id: "shallows",
    index: 0,
    name: "漂流浅瀬",
    subtitle: "小さな足場から、最初の漁港をつくる",
    icon: "🏝️",
    color: "#38bdf8",
    source: "fish",
    product: "grilled",
    sourceName: "浅瀬の魚群",
    productName: "焼き魚",
    processorName: "焼き台",
    workerName: "漁師",
    transportName: "加工係",
    deliveryName: "配達いかだ",
    sourceEvery: 1600,
    processMs: 1500,
    orderSize: 3,
    orderReward: 160,
    blueReward: 2,
    restorationReward: 2,
    expandCost: 60,
    sourceAutoCost: 90,
    processAutoCost: 150,
    deliveryAutoCost: 280,
    unlockCost: 650,
  },
  {
    id: "coral",
    index: 1,
    name: "サンゴ礁",
    subtitle: "白化したサンゴと貝の海をよみがえらせる",
    icon: "🪸",
    color: "#2dd4bf",
    source: "shell",
    product: "pearl",
    sourceName: "真珠貝の棚",
    productName: "再生真珠",
    processorName: "貝加工台",
    workerName: "養殖係",
    transportName: "サンゴ運搬員",
    deliveryName: "礁湖ボート",
    sourceEvery: 1900,
    processMs: 2200,
    orderSize: 4,
    orderReward: 360,
    blueReward: 3,
    restorationReward: 3,
    expandCost: 240,
    sourceAutoCost: 420,
    processAutoCost: 680,
    deliveryAutoCost: 1100,
    unlockCost: 2200,
  },
  {
    id: "islands",
    index: 2,
    name: "群島漁場",
    subtitle: "島々を冷凍航路でつなぐ",
    icon: "⛵",
    color: "#0ea5e9",
    source: "tuna",
    product: "frozen",
    sourceName: "マグロ漁場",
    productName: "冷凍マグロ",
    processorName: "洋上冷凍庫",
    workerName: "漁船船長",
    transportName: "冷蔵運搬員",
    deliveryName: "交易船",
    sourceEvery: 2300,
    processMs: 2900,
    orderSize: 5,
    orderReward: 820,
    blueReward: 4,
    restorationReward: 4,
    expandCost: 780,
    sourceAutoCost: 1300,
    processAutoCost: 2100,
    deliveryAutoCost: 3400,
    unlockCost: 6800,
  },
  {
    id: "openSea",
    index: 3,
    name: "外洋",
    subtitle: "波と嵐を越え、船団の燃料をつくる",
    icon: "🌊",
    color: "#2563eb",
    source: "plankton",
    product: "biofuel",
    sourceName: "外洋採取区",
    productName: "バイオ燃料",
    processorName: "洋上培養船",
    workerName: "採取船団",
    transportName: "航海管理AI",
    deliveryName: "燃料輸送船",
    sourceEvery: 2600,
    processMs: 3600,
    orderSize: 6,
    orderReward: 1900,
    blueReward: 5,
    restorationReward: 5,
    expandCost: 2400,
    sourceAutoCost: 3900,
    processAutoCost: 6200,
    deliveryAutoCost: 9800,
    unlockCost: 19000,
  },
  {
    id: "abyss",
    index: 4,
    name: "深海峡谷",
    subtitle: "潜水艇で暗い海底の資源を探す",
    icon: "🛸",
    color: "#4338ca",
    source: "deepOre",
    product: "alloy",
    sourceName: "深海鉱床",
    productName: "耐圧合金",
    processorName: "水圧精錬所",
    workerName: "無人潜水艇",
    transportName: "深海搬送ドローン",
    deliveryName: "浮上カプセル",
    sourceEvery: 3100,
    processMs: 4400,
    orderSize: 5,
    orderReward: 4600,
    blueReward: 7,
    restorationReward: 7,
    expandCost: 7200,
    sourceAutoCost: 11000,
    processAutoCost: 17500,
    deliveryAutoCost: 28000,
    unlockCost: 52000,
  },
  {
    id: "volcano",
    index: 5,
    name: "海底火山帯",
    subtitle: "危険な熱を、都市を動かす電力へ変える",
    icon: "🌋",
    color: "#ea580c",
    source: "heatOre",
    product: "core",
    sourceName: "熱水噴出孔",
    productName: "地熱コア",
    processorName: "海底地熱炉",
    workerName: "耐熱採掘ロボ",
    transportName: "耐熱搬送機",
    deliveryName: "送電カプセル",
    sourceEvery: 3600,
    processMs: 5200,
    orderSize: 4,
    orderReward: 10500,
    blueReward: 9,
    restorationReward: 9,
    expandCost: 19000,
    sourceAutoCost: 30000,
    processAutoCost: 48000,
    deliveryAutoCost: 76000,
    unlockCost: 140000,
  },
  {
    id: "iceCity",
    index: 6,
    name: "氷海と海底都市",
    subtitle: "氷の下に眠る都市を完成させる最終海域",
    icon: "🏙️",
    color: "#67e8f9",
    source: "iceFish",
    product: "cityPart",
    sourceName: "氷下探索区",
    productName: "海底都市パーツ",
    processorName: "都市組立ドック",
    workerName: "砕氷調査船",
    transportName: "都市建設ロボ",
    deliveryName: "都市中枢AI",
    sourceEvery: 4200,
    processMs: 6200,
    orderSize: 3,
    orderReward: 25000,
    blueReward: 12,
    restorationReward: 12,
    expandCost: 52000,
    sourceAutoCost: 82000,
    processAutoCost: 130000,
    deliveryAutoCost: 210000,
    unlockCost: 0,
  },
];

export const oceanAreaById = new Map<OceanAreaId, OceanAreaDef>(
  oceanAreas.map((area) => [area.id, area]),
);

export const oceanArea = (id: OceanAreaId) => oceanAreaById.get(id)!;
